// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApxPjAsEB7Gre_PsI769sblZiw5ch04Pw',
    appId: '1:160751823241:web:92b7b92248e49faa761958',
    messagingSenderId: '160751823241',
    projectId: 'yobit-54b2a',
    authDomain: 'yobit-54b2a.firebaseapp.com',
    storageBucket: 'yobit-54b2a.appspot.com',
    measurementId: 'G-QJPHJ77KC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiqH6qs4QKWW8zBu8PtFrDeFK2CutEB8',
    appId: '1:160751823241:android:f1af3740cfc9aefd761958',
    messagingSenderId: '160751823241',
    projectId: 'yobit-54b2a',
    storageBucket: 'yobit-54b2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCdE0w6z3P0YGJaOf2LqEgfN3_IPbeeg',
    appId: '1:160751823241:ios:6f4beb349623288c761958',
    messagingSenderId: '160751823241',
    projectId: 'yobit-54b2a',
    storageBucket: 'yobit-54b2a.appspot.com',
    iosClientId: '160751823241-dqhelv844l8belh248nkpb9t07um70pe.apps.googleusercontent.com',
    iosBundleId: 'com.yobit.app',
  );
}
